# 注册到eureka-server上
eureka:
  instance:
    # 主机名称
    hostname: ${spring.cloud.client.ip-address}
    # 自定义实例ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 显示IP地址
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 过期剔除时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10
  client:
    # 是否将eureka自身作为应用注册到eureka注册中心
    register-with-eureka: true
    # 客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: true
    # 设置拉取服务注册信息时间（缺省为60s）
    registry-fetch-interval-seconds: 30
    # Eureka服务
    serviceUrl:
      #服务注册中心地址
      defaultZone: http://192.168.20.11:8700/eureka/
  healthcheck:
    # 开启健康检查
    enabled: true
spring:
  redis:
    timeout: 6000ms
    host: 132.232.196.177
    port: 16379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: 1000ms
  kafka:
    bootstrap-servers: 45.40.246.109:9092
    consumer:
      group-id: promotion-test
      enable-auto-commit: false
      session-timeout-ms: 15000
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 0
      batch.size: 16384
      linger.ms: 1
      acks: 1
      buffer.memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # 数据库配置
  datasource:
    name: qc_user
    url: jdbc:mysql://dcdbt-qn07qqr4.sql.tencentcdb.com:7/qc_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: test_shop
    password: dIJ6_pWKTe
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      # encrypt password
      #filters: config,stat,wall,log4j
      use-global-data-source-stat: true
      connection-init-sqls:
        - set names utf8mb4

sensorsUrl: http://jijixian.datasink.sensorsdata.cn/sa?project=default&token=19a8dda602bf9603

